### ISSUE TITLE
unloadedImages never reaches 0

### ISSUE THREAD

**Issue by lactose** [weblinc/jquery-imageready#6]
by setting the variable unloadedImages as such:

unloadedImages = $images.length; //this is an array length

in the loaded() function, decrementing this value will never reach 0 length needed to trigger callback function.

**Comment by jsantell** [comment]
After the decrement, on [L13](https://github.com/weblinc/jquery-imageready/blob/master/jquery.imageready.js#L13) the truthiness of unloadedImages is checked -- if it's 0, it'll fire the last callback function. The test case in the repo and others work for me -- do you have an instance/jsFiddle where this isn't the case?

**Comment by lactose** [comment]
my apologies, this turned out to be an unrelated issue. thanks for the quick response @jsantell

**Comment by jsantell** [comment]
no prob, cheers! :+1:
